### ISSUE TITLE
Template on develop is broken

### ISSUE THREAD

**Issue by kdawgwilk** [CocoaPods/pod-template#186]
@fulldecent Attempted to use the new template on `develop` that has somewhat support for SPM but got this exception:

<details>
<summary>`~/Desktop $ pod lib create --template-url='file:///Users/username/Desktop/pod-template' GraphQL-Swift`</summary>
```
Cloning `file:///Users/username/Desktop/pod-template` into `GraphQL-Swift`.
Configuring GraphQL-Swift template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide:
 - http://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and click links to open in a browser. )


What language do you want to use?? [ Swift / ObjC ]
 > Swift

Would you like to include a demo application with your library? [ Yes / No ]
 > No

Which testing frameworks will you use? [ Quick / None ]
 > Quick

Would you like to do view based testing? [ Yes / No ]
 > No
/Users/kwilkinson/Desktop/GraphQL-Swift/configurator/ProjectManipulator.rb:55:in `remove_demo_project': undefined method `remove_from_project' for nil:NilClass (NoMethodError)
	from /Users/username/Desktop/GraphQL-Swift/configurator/ProjectManipulator.rb:31:in `run'
	from /Users/username/Desktop/GraphQL-Swift/configurator/SwiftConfigurator.rb:54:in `perform'
	from /Users/username/Desktop/GraphQL-Swift/configurator/SwiftConfigurator.rb:13:in `perform'
	from /Users/username/Desktop/GraphQL-Swift/configurator/MainConfigurator.rb:54:in `run'
	from ./configure:9:in `<main>'

To learn more about the template see `file:///Users/username/Desktop/pod-template`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.
```
</details>

**Comment by fulldecent** [comment]
Thank you. I added this into the complete PR at https://github.com/CocoaPods/pod-template/pull/187

**Comment by orta** [comment]
👍
