### ISSUE TITLE
Create myLib failed.

### ISSUE THREAD

**Issue by xs23933** [CocoaPods/pod-template#220]
/Library/Ruby/Gems/2.3.0/gems/atomos-0.1.1/lib/atomos.rb:8:in `atomic_write': undefined method `tmpdir' for Dir:Class (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/xcodeproj-1.5.5/lib/xcodeproj/project.rb:354:in `save'
	from /Users/***/code/Pods/myLib/setup/ProjectManipulator.rb:33:in `run'
	from /Users/***/code/Pods/myLib/setup/ConfigureiOS.rb:73:in `perform'
	from /Users/***/code/Pods/myLib/setup/ConfigureiOS.rb:7:in `perform'
	from /Users/***/code/Pods/myLib/setup/TemplateConfigurator.rb:79:in `run'
	from ./configure:9:in `<main>'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.

what happend. who know

**Comment by xs23933** [comment]
ok, fininsh.

sudo gem install atomos
update atomos to 0.1.2 can do something.
