### ISSUE TITLE
cannot load such file -- xcodeproj (LoadError)

### ISSUE THREAD

**Issue by liao0322** [CocoaPods/pod-template#222]
Cloning `https://github.com/CocoaPods/pod-template.git` into `XFTestLib`.
Configuring XFTestLib template.
Traceback (most recent call last):
	6: from ./configure:4:in `<main>'
	5: from ./configure:4:in `each'
	4: from ./configure:5:in `block in <main>'
	3: from ./configure:5:in `require_relative'
	2: from /Users/liaoxf/Desktop/FengLeiModularizationLib/Bases/XFTestLib/setup/ProjectManipulator.rb:1:in `<top (required)>'
	1: from /usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/Cellar/ruby/2.5.0/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- xcodeproj (LoadError)

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.

**Comment by jugutier** [comment]
Hi! try "gem install xcodeproj" and if that doesn't work you might need to use --user-install or rbenv/rbm

**Comment by rogerluan** [comment]
If you'd rather use bundler instead of installing the gem to your system, add `xcodeproj` to your `Gemfile` and add `require 'bundler/setup'` before requiring xcodeproj, i.e.:

```ruby
require 'bundler/setup' # Required so that the gem below loads from bundler, not system's gems.
require 'xcodeproj'
```

**Comment by UbaidillahGit** [comment]
`sudo gem install xcodeproj` works for me

**Comment by alikperislam** [comment]
sudo gem install xcodeproj works for me. Thank u bro thank u
